apiVersion: ml.aws.caas.upbound.io/v1alpha1
kind: Service
metadata:
  name: webinar-ml-01
  namespace: default
spec:
  parameters:
    id: webinar-ml-01
    region: eu-central-1
    nodes:
      count: 1
      instanceType: g5.12xlarge
      diskSize: 100
    jupyter:
      - name: notebook
        namespace: default
      - name: hf-token
        namespace: default
